# Generated by Django 5.1.3 on 2025-03-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
    ]
