# Generated by Django 5.1.3 on 2025-03-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_auto_20250319_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workdetail',
            old_name='office_name_key',
            new_name='office_name',
        ),
    ]
