# Generated by Django 5.1.3 on 2025-04-04 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0003_rename_office_name_key_workdetail_office_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff_name', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=255)),
            ],
        ),
    ]
