# Generated by Django 5.1.3 on 2025-04-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0004_historylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='end_date',
            new_name='edu_end_date',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='start_date',
            new_name='edu_start_date',
        ),
    ]
